name: CI-Release

on:
  push:
    branches: [ release ]

env:
  GAR_LOCATION: europe-west3-npm.pkg.dev/prod-343209/maki-npm-repo
  PROJECT_ID: prod-343209
  REGION: europe-west3

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      packages: 'write'
      id-token: 'write'
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
      
      - name: "Prepare node"
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://${{ env.GAR_LOCATION }}'
          token: '${{ steps.auth.outputs.access_token }}'
          always-auth: 'true'

      - name: "Publish"
      - run: |
          cd ./package
          npm publish
          
