name: CI-Release
on:
  push:
    branches: [ "release" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: install sass and compile css
        run: |
          npm install -g sass
          sass --update themes/maki/maki-light/theme.scss:package/theme.css

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authenticate to Google Cloud (if using workload identity pool)
        if: ${{ secrets.WIF_PROVIDER != '' }}  # Skip if not using pool
        uses: google-github-actions/auth@v1
        with:
          workload_identity_pool: ${{ secrets.WIF_PROVIDER }}
          credentials_json: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://europe-west3-npm.pkg.dev/ityreh-prod/maki-npm/'
      - name: package and deploy theme
        run: |
          cd ./package
          npm publish
