name: CI-Release
on:
  push:
    branches: [ "release" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: install sass and compile css
        run: |
          npm install -g sass
          sass --update themes/maki/maki-light/theme.scss:package/theme.css

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
          audience: "https://artifactregistry.googleapis.com/"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://europe-west3-npm.pkg.dev/prod-343209/maki-npm-repo'
      - name: package and deploy theme
        run: |
          cd ./package
          npm publish
