name: CI-Release
on:
  push:
    branches: [ release ]
  release:
    types: [ published ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: install sass and compile css
        run: |
          npm install -g sass
          sass --update themes/maki/maki-light/theme.scss:package/theme.css

      - name: package and deploy theme
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_NPM_PUBLISH }}
        run: |
          cd ./package
          npm publish
        
